wandb_version: 1

emb_size:
  value: 256
epochs:
  value: 5
hidden_size:
  value: 256
input_size:
  value: 768
layertype:
  value: OrthoLinear
lr:
  value: 0.0001
output_size:
  value: 5
seed_idx:
  value: 0
tasks:
  value: cat
test_size:
  value: 0.2
