wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.11.8
    start_time: 1721845521.254427
    t:
      1:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 53
      - 55
      - 71
      3:
      - 1
      - 16
      - 23
      4: 3.11.8
      5: 0.13.11
      6: 4.40.1
      8:
      - 5
    visualize:
      best_avg_ep_AUC:
        panel_config:
          fieldSettings:
            label: task
            value: best_avg_ep_AUC
          panelDefId: wandb/bar/v0
          stringSettings:
            title: best_avg_ep_AUC
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: best_avg_ep_AUC_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      best_avg_ep_tloss:
        panel_config:
          fieldSettings:
            label: task
            value: best_avg_ep_tloss
          panelDefId: wandb/bar/v0
          stringSettings:
            title: best_avg_ep_tloss
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: best_avg_ep_tloss_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      best_avg_ep_vloss:
        panel_config:
          fieldSettings:
            label: task
            value: best_avg_ep_vloss
          panelDefId: wandb/bar/v0
          stringSettings:
            title: best_avg_ep_vloss
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: best_avg_ep_vloss_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      best_own_ep:
        panel_config:
          fieldSettings:
            label: task
            value: best_own_ep
          panelDefId: wandb/bar/v0
          stringSettings:
            title: best_own_ep
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: best_own_ep_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      best_own_ep_AUC:
        panel_config:
          fieldSettings:
            label: task
            value: best_own_ep_AUC
          panelDefId: wandb/bar/v0
          stringSettings:
            title: best_own_ep_AUC
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: best_own_ep_AUC_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      best_own_ep_tloss:
        panel_config:
          fieldSettings:
            label: task
            value: best_own_ep_tloss
          panelDefId: wandb/bar/v0
          stringSettings:
            title: best_own_ep_tloss
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: best_own_ep_tloss_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      best_own_ep_vloss:
        panel_config:
          fieldSettings:
            label: task
            value: best_own_ep_vloss
          panelDefId: wandb/bar/v0
          stringSettings:
            title: best_own_ep_vloss
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: best_own_ep_vloss_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
dataset:
  desc: null
  value: oral_data
emb_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 32
hidden_size:
  desc: null
  value: 256
init_group:
  desc: null
  value: mtask
init_notes:
  desc: null
  value: None
init_project:
  desc: null
  value: Multitask_Class_Oral
input_size:
  desc: null
  value: 768
labelcol:
  desc: null
  value: EPACategoryIndex
layertype:
  desc: null
  value: OrthoLinear
lr:
  desc: null
  value: 0.0001
output_size:
  desc: null
  value: 5
seed_idx:
  desc: null
  value: 4
smilescol:
  desc: null
  value: SMILES
task:
  desc: null
  value: all except human
testprop:
  desc: null
  value: 0.2
