wandb_version: 1

init_project:
  desc: null
  value: Multitask Class Oral Test
init_group:
  desc: null
  value: humval
init_notes:
  desc: null
  value: None
dataset:
  desc: null
  value: human_data
train_data:
  desc: null
  value:
  - man
  - mouse
  - woman
test_data:
  desc: null
  value:
  - man
  - woman
seed_idx:
  desc: null
  value: 1
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.0001
testprop:
  desc: null
  value: 0.2
input_size:
  desc: null
  value: 768
emb_size:
  desc: null
  value: 256
hidden_size:
  desc: null
  value: 256
output_size:
  desc: null
  value: 5
layertype:
  desc: null
  value: OrthoLinear
smilescol:
  desc: null
  value: SMILES
labelcol:
  desc: null
  value: EPACategoryIndex
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.42.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721926954.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 1
      - 16
      - 23
      4: 3.11.8
      5: 0.16.6
      6: 4.42.4
      8:
      - 5
      13: linux-x86_64
    visualize:
      best_avg_ep_tloss:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: task
            value: best_avg_ep_tloss
          stringSettings:
            title: best_avg_ep_tloss
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: best_avg_ep_tloss_table
                fields: []
      best_avg_ep_vloss:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: task
            value: best_avg_ep_vloss
          stringSettings:
            title: best_avg_ep_vloss
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: best_avg_ep_vloss_table
                fields: []
      best_avg_ep_AUC:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: task
            value: best_avg_ep_AUC
          stringSettings:
            title: best_avg_ep_AUC
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: best_avg_ep_AUC_table
                fields: []
      best_own_ep:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: task
            value: best_own_ep
          stringSettings:
            title: best_own_ep
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: best_own_ep_table
                fields: []
      best_own_ep_tloss:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: task
            value: best_own_ep_tloss
          stringSettings:
            title: best_own_ep_tloss
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: best_own_ep_tloss_table
                fields: []
      best_own_ep_vloss:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: task
            value: best_own_ep_vloss
          stringSettings:
            title: best_own_ep_vloss
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: best_own_ep_vloss_table
                fields: []
      best_own_ep_AUC:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: task
            value: best_own_ep_AUC
          stringSettings:
            title: best_own_ep_AUC
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: best_own_ep_AUC_table
                fields: []
