wandb_version: 1

init_project:
  desc: null
  value: Multitask Class Oral Test
init_group:
  desc: null
  value: mouse_bi
init_notes:
  desc: null
  value: None
dataset:
  desc: null
  value: single_data/mouse
train_data:
  desc: null
  value:
  - mouse
test_data:
  desc: null
  value:
  - mouse
seed_idx:
  desc: null
  value: 1
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.0001
testprop:
  desc: null
  value: 0.2
input_size:
  desc: null
  value: 768
emb_size:
  desc: null
  value: 256
hidden_size:
  desc: null
  value: 256
output_size:
  desc: null
  value: 1
layertype:
  desc: null
  value: OrthoLinear
smilescol:
  desc: null
  value: SMILES
labelcol:
  desc: null
  value: tox2000
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.42.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721947815.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 1
      - 16
      - 23
      4: 3.11.8
      5: 0.16.6
      6: 4.42.4
      8:
      - 5
      13: linux-x86_64
