init_project: "Multitask Class Oral"
init_group: "mtask"
# init_notes: "multi run"
dataset: "oral_data"
task: "all except human"
seed_idx: 0
epochs: 10
lr: 0.0001
testprop: 0.2
input_size: 768
emb_size: 256
hidden_size: 256
output_size: 5
layertype: "OrthoLinear"
smilescol: "SMILES"
labelcol: "EPACategoryIndex"
