wandb_version: 1

batch_size:
  value: 64
emb_size:
  value: 512
epochs:
  value: 32
hidden_size:
  value: 256
input_size:
  value: 768
labelcol:
  value: Toxicity
layer_sizes:
  value:
  - 256
  - 128
  - 64
  - 32
  - 16
layertype:
  value: OrthoLinear
lr:
  value: 1.0e-05
output_size:
  value: 1
seed_idx:
  value: 0
smilescol:
  value: SMILES
task:
  value: hepa
test_size:
  value: 0.2
