wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.11.8
    start_time: 1722285389.625353
    t:
      1:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 53
      - 55
      - 71
      3:
      - 1
      - 16
      - 23
      4: 3.11.8
      5: 0.13.11
      6: 4.40.1
      8:
      - 5
dataset:
  desc: null
  value: single_data/mouse
emb_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 32
hidden_size:
  desc: null
  value: 256
init_group:
  desc: null
  value: m_mouse
init_notes:
  desc: null
  value: multi mouse
init_project:
  desc: null
  value: Multitask_Class_Oral
input_size:
  desc: null
  value: 768
labelcol:
  desc: null
  value: EPACategoryIndex
layertype:
  desc: null
  value: OrthoLinear
lr:
  desc: null
  value: 0.0001
output_size:
  desc: null
  value: 5
seed_idx:
  desc: null
  value: 1
smilescol:
  desc: null
  value: SMILES
task:
  desc: null
  value: mouse
testprop:
  desc: null
  value: 0.2
