wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.42.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721252069.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.11.8
      5: 0.16.6
      6: 4.42.4
      8:
      - 5
      13: linux-x86_64
emb_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 5
hidden_size:
  desc: null
  value: 256
input_size:
  desc: null
  value: 768
layertype:
  desc: null
  value: OrthoLinear
lr:
  desc: null
  value: 0.0001
output_size:
  desc: null
  value: 5
seed_idx:
  desc: null
  value: 2
tasks:
  desc: null
  value: chicken
test_size:
  desc: null
  value: 0.2
